### ISSUE TITLE
Mod broken after 1.08 update?

### ISSUE THREAD

**Issue by joverton13** [Gerkiz/RPG#9] opened 2022-05-20 23:10 UTC
I just installed the update, and it looks to have broken the mod.  If I click "RPG" in the GUI, nothing opens.  I see the Spells menu, but trying to use fish to cast a spell doesn't work; the screen flashes red, I lose some HP, and nothing else happens (nothing is summoned).

Will be happy to provide more information; just let me know what you want and where to get it.

Thanks! (I love this mod...was sad to see it broken!)

**Comment by Gerkiz** [comment] 2022-05-23 10:02
Hi!

What version are you currently running?

I'm using 1.0.8 in the video below. And afaik everything seems to work?

https://user-images.githubusercontent.com/39602942/169795332-2c459d46-62a0-4461-a841-c4cacd969c58.mp4

**Comment by joverton13** [comment] 2022-05-30 19:44
So sorry for the delay; I was away for several days.

When I installed 1.08, it stopped working.  If I downgraded to 1.06, it started working again.  

Not sure why, but maybe it has to do with other surfaces?  I'm playing with Mobile Base and Space Exploration, and I have always found that while I could open the RPG window on other surfaces, I could not adjust stats or use the fish powers unless I was on the main planet surface (things like crafting speed, run speed and inventory space still worked, at least most of the time).

I will try to find a time in the next day or two to reinstall 1.08, and record it to show you.

**Comment by joverton13** [comment] 2022-05-31 17:58
https://user-images.githubusercontent.com/42623344/171253745-2477078e-bfab-4a79-a37f-c6b16798dbb5.mp4

**Comment by joverton13** [comment] 2022-05-31 18:09
https://user-images.githubusercontent.com/42623344/171255630-053b6ac6-2187-4acd-b11e-42a8623948da.mp4

**Comment by joverton13** [comment] 2022-05-31 18:19
My installed mods, if that helps.  Keep in mind, this broke when going from RPG 1.06 - 1.08.  I don't have 1.07, so I don't know if that's when this happened or not
![Screenshot 2022-05-31 141055](https://user-images.githubusercontent.com/42623344/171256925-f71b27ce-c496-44de-b690-193a18be185b.jpg)
![Screenshot 2022-05-31 141118](https://user-images.githubusercontent.com/42623344/171256943-32a81308-4ee7-4be9-969d-fc32743967b4.jpg)
![Screenshot 2022-05-
![Screenshot 2022-05-31 141202](https://user-images.githubusercontent.com/42623344/171256993-d7774cfa-9ee9-4558-ac29-c54835021e70.jpg)
31 141140](https://user-images.githubusercontent.com/42623344/171256968-9c18fc88-126d-499d-a19f-5e72fdc2a086.jpg)
![Screenshot 2022-05-31 141202](https://user-images.githubusercontent.com/42623344/171257246-0c075f1b-6135-42ed-88bb-d94b12e49349.jpg)
![Screenshot 2022-05-31 141249](https://user-images.githubusercontent.com/42623344/171257266-7f44f981-f035-4e22-9da3-c6137092e276.jpg)
![Screenshot 2022-05-31 141308](https://user-images.githubusercontent.com/42623344/171257292-2db4a0c7-c3d6-430b-bfc3-96f42a653002.jpg)
.

**Comment by joverton13** [comment] 2022-06-02 18:05
Absolutely!

1.06: https://www.dropbox.com/s/94emxr07wt3q2sx/RPG_106_test.zip?dl=0
1.08: https://www.dropbox.com/s/dcpyuve9s3i68nt/RPG_108_test.zip?dl=0

Please let  me know if you have any issues accessing these.

**Comment by Gerkiz** [comment] 2022-06-03 15:15
This is now fixed in 1.0.9.

Sorry about the migration issue!

Also, your save has the mod: [RE:Storage Energistics](https://mods.factorio.com/mod/re_storage_energistics) which is making your game lag crazy. Consider removing this mod or report this issue to the author 👍

**Comment by joverton13** [comment] 2022-06-07 15:57
It works!  Thanks so much!!

Yeah, I know SE is a hog...However, for my manner of playing (more "idle") it's not so bad, and the QoL it provides is much better...but thanks for the suggestion :)

I see you added more spells....very cool!  But what does "Charge" do?

Thanks again for the fix :)

**Comment by Gerkiz** [comment] 2022-06-10 20:18
Thank you for your report! I'll check out the zip files 👍

**Comment by Gerkiz** [comment] 2022-06-10 20:52
How odd. I can't seem to reproduce this?

I tried loading `Sea_001.zip`, and I checked the rpg menu, looks like this:
![image](https://user-images.githubusercontent.com/39602942/173148111-da46d89a-0b42-4cac-9cb2-370920660c2b.png)

I then tried to add points to various skills and that went well.

Thereafter I saved the game as `Sea_002.zip` and loaded that. Picture below:
![image](https://user-images.githubusercontent.com/39602942/173148271-e06bf3df-9e8c-4567-83a8-4c35eb4e28d6.png)


Could you please post your `factorio-current.log` and `factorio-previous.log` found in `%appdata/roaming/factorio`

Thanks!

**Comment by Gerkiz** [comment] 2022-06-10 20:55
I tried creating a new freeplay run and did the same as you. But everything checks out? ✅

**Comment by joverton13** [comment] 2022-06-12 18:50
[factorio-previous.log](https://github.com/Gerkiz/RPG/files/8886535/factorio-previous.log)

Hmm...No idea what's going on then...

This is the only log with data - not sure if this helps at all...because it's dated today, and currently it's working on my end.

If It happens again, I'll post the relevant logs.

Quick question:  Do you know if there's a "cache" that could be corrupted at all? Recently I've gotten weird mod errors that I don't know why they are happening, and this issue above with the truncating everything after STR have been weird, and I can't figure out why (I'll enable and disable mods, but can't think of any rhyme or reason why it's happening).

**Comment by Gerkiz** [comment] 2022-06-30 12:53
The `factorio-previous.log` does not show any errors. If you do manage to find a way to replicate the issue do reopen this issue.

**Closed by Gerkiz** 2022-06-30 12:53 UTC
Labels: need more information
